name: renva0
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  get: ^4.6.6
  flutter_svg: ^2.1.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  dio:
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  get_storage: ^2.1.1
  pinput: ^5.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.3.2

# FlutterGen configuration
flutter_gen:
  integrations:
    flutter_svg: true


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/arrows/
    - assets/icons/document/
    - assets/icons/emojis/
    - assets/icons/essentials/
    - assets/icons/messages/
    - assets/images/logo/
    - assets/translations/