// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _ar = {
  "common": {
    "welcome_to": "مرحبًا بك في",
    "back": "رجوع",
    "go_back": "رجوع",
    "cancel": "إلغاء",
    "confirm": "تأكيد",
    "save": "حفظ",
    "delete": "حذف",
    "edit": "تعديل",
    "add": "إضافة",
    "remove": "إزالة",
    "search": "بحث",
    "filter": "تصفية",
    "sort": "ترتيب",
    "loading": "جاري التحميل...",
    "error": "خطأ",
    "success": "نجح",
    "warning": "تحذير",
    "info": "معلومات",
    "yes": "نعم",
    "no": "لا",
    "ok": "موافق",
    "done": "تم",
    "next": "التالي",
    "previous": "السابق",
    "skip": "تخطي",
    "retry": "إعادة المحاولة",
    "refresh": "تحديث",
    "close": "إغلاق",
    "open": "فتح",
    "select": "اختيار",
    "upload": "رفع",
    "download": "تحميل",
    "send": "إرسال",
    "receive": "استقبال",
    "view": "عرض",
    "hide": "إخفاء",
    "show": "إظهار",
    "user": "المستخدم",
    "no_phone": "لا يوجد هاتف",
    "continue": "المتابعة",
    "submit": "إرسال",
    "from": "من",
    "to": "إلى",
    "unknown_service": "خدمة غير معروفة",
    "unknown_subcategory": "فئة فرعية غير معروفة",
    "unknown_location": "موقع غير معروف",
    "unknown_user": "مستخدم غير معروف",
    "no_description": "لا يوجد وصف",
    "not_specified": "غير محدد",
    "date_not_specified": "التاريخ غير محدد",
    "time_not_specified": "الوقت غير محدد",
    "price_not_specified": "السعر غير محدد",
    "no_description_available": "لا يوجد وصف متاح",
    "service_request": "طلب خدمة",
    "some_error": "حدث خطأ ما"
  },
  "auth": {
    "login": "تسجيل الدخول",
    "signup": "إنشاء حساب",
    "logout": "تسجيل الخروج",
    "register": "تسجيل",
    "login_title": "سجّل الدخول إلى حسابك.",
    "login_subtitle": "أدخل المعلومات التالية للوصول إلى حسابك",
    "signup_title": "إنشاء حساب جديد",
    "signup_subtitle": "أضف معلوماتك لإنشاء حساب جديد",
    "phone_number": "رقم الهاتف",
    "phone_placeholder": "مثال: +963 111 222 333",
    "password": "كلمة المرور",
    "password_placeholder": "••• ••• •••",
    "confirm_password": "تأكيد كلمة المرور",
    "confirm_password_placeholder": "تأكيد كلمة المرور",
    "forgot_password": "نسيت كلمة المرور؟",
    "join_as_guest": "انضم كضيف",
    "add_strong_password": "أضف كلمة مرور قوية",
    "create_account": "إنشاء الحساب",
    "have_account": "هل لديك حساب بالفعل؟",
    "no_account": "ليس لديك حساب؟",
    "sign_in_instead": "تسجيل الدخول بدلاً من ذلك",
    "sign_up_instead": "إنشاء حساب بدلاً من ذلك",
    "forgot_password_title": "نسيت كلمة المرور",
    "forgot_password_subtitle": "أدخل رقم هاتفك لاستلام رمز التحقق",
    "reset_password_title": "إعادة تعيين كلمة المرور",
    "reset_password_subtitle": "أدخل كلمة المرور الجديدة",
    "new_password": "كلمة المرور الجديدة",
    "new_password_placeholder": "أدخل كلمة المرور الجديدة",
    "password_changed": "تم تغيير كلمة المرور بنجاح",
    "verification_code_sent": "تم إرسال رمز التحقق بنجاح",
    "verification_code_resent": "تم إعادة إرسال رمز التحقق"
  },
  "verification": {
    "title": "تحقق من رقم الهاتف",
    "subtitle": "أدخل الرمز المرسل إلى",
    "code_label": "رمز التحقق",
    "code_placeholder": "0000",
    "resend_code": "إعادة إرسال الرمز",
    "resend_in": "إعادة إرسال الرمز خلال",
    "seconds": "ثانية",
    "verify": "تحقق",
    "verification_sent": "تم إرسال رمز التحقق بنجاح",
    "verification_failed": "فشل التحقق",
    "invalid_code": "رمز التحقق غير صحيح",
    "code_expired": "انتهت صلاحية رمز التحقق"
  },
  "profile": {
    "complete_profile": "إكمال المعلومات",
    "complete_subtitle": "أضف معلوماتك لإنشاء حساب جديد",
    "full_name": "الاسم الكامل",
    "full_name_placeholder": "اسم المستخدم",
    "last_name": "الاسم الأخير",
    "last_name_placeholder": "الاسم الأخير",
    "email": "البريد الإلكتروني",
    "email_placeholder": "user.name@gmail.com",
    "national_number": "الرقم القومي",
    "national_number_placeholder": "أضف الرقم القومي",
    "gender": "الجنس",
    "gender_placeholder": "ذكر",
    "male": "ذكر",
    "female": "أنثى",
    "profile_picture": "صورة الملف الشخصي",
    "add_photo": "إضافة صورة",
    "add_profile_photo": "إضافة صورة الملف الشخصي",
    "id_photo": "صورة الهوية",
    "tap_to_add": "اضغط للإضافة",
    "profile_completed": "تم إكمال الملف الشخصي بنجاح",
    "profile_not_saved": "لن يتم حفظ معلومات ملفك الشخصي. هل تريد الرجوع؟",
    "edit_profile": "تعديل الملف الشخصي",
    "name": "الاسم",
    "phone_number": "رقم الهاتف",
    "phone_placeholder": "+999 123 456 78",
    "select_profile_photo": "اختر صورة الملف الشخصي",
    "select_id_photo": "اختر صورة الهوية",
    "take_new_photo": "التقاط صورة جديدة",
    "choose_from_gallery": "اختر من المعرض",
    "select_gender": "اختر الجنس",
    "failed_to_load": "فشل في تحميل الملف الشخصي",
    "retry": "إعادة المحاولة",
    "account": "الحساب",
    "service_provider": "مقدم الخدمة",
    "provider_info": "مقدم الخدمة: {name}",
    "rating": "التقييم: {rating}",
    "orders": "الطلبات",
    "points": "النقاط",
    "loyalty_points": "نقاط الولاء",
    "payment": "الدفع",
    "login_as_user": "تسجيل الدخول كمستخدم",
    "login_as_provider": "تسجيل الدخول كمقدم خدمة",
    "select_image_source": "اختر مصدر الصورة",
    "camera": "الكاميرا",
    "gallery": "المعرض",
    "remove_picture": "إزالة الصورة",
    "remove_picture_confirm": "هل أنت متأكد من أنك تريد إزالة صورتك؟",
    "language_changed_to": "تم تغيير اللغة إلى {language}",
    "language_failed": "فشل في تغيير اللغة",
    "load_failed": "فشل في تحميل بيانات الملف الشخصي. يرجى المحاولة مرة أخرى.",
    "picture_updated": "تم تحديث صورة الملف الشخصي بنجاح",
    "picture_invalid": "ملف الصورة المحدد غير صحيح",
    "image_selection_failed": "فشل في اختيار الصورة",
    "notifications_enabled": "تم تفعيل الإشعارات",
    "notifications_disabled": "تم إلغاء تفعيل الإشعارات",
    "logout_title": "تسجيل الخروج",
    "logout_confirm": "هل أنت متأكد من أنك تريد تسجيل الخروج؟",
    "logout_success": "تم تسجيل الخروج بنجاح",
    "logout_offline": "تم تسجيل الخروج محلياً بسبب خطأ في الشبكة",
    "logout_failed": "فشل في تسجيل الخروج بشكل صحيح. يرجى المحاولة مرة أخرى.",
    "delete_account_title": "حذف الحساب",
    "delete_account_confirm": "هل أنت متأكد من أنك تريد حذف حسابك؟ هذا الإجراء لا يمكن التراجع عنه.",
    "delete_final_title": "التأكيد النهائي",
    "delete_final_confirm": "سيؤدي هذا إلى حذف حسابك وجميع البيانات نهائياً. هل أنت متأكد تماماً؟",
    "deleting": "جاري الحذف...",
    "delete_forever": "حذف نهائي",
    "delete_success": "تم حذف الحساب بنجاح",
    "delete_failed": "فشل في حذف الحساب: {error}",
    "no_auth_token": "لم يتم العثور على رمز المصادقة",
    "user_id_not_found": "لم يتم العثور على معرف المستخدم",
    "loyalty_points_title": "نقاط الولاء",
    "loyalty_points_message": "لديك {points} نقطة ولاء",
    "loyalty_points_earn_more": "احصل على المزيد من النقاط عن طريق إكمال الطلبات!",
    "payment_methods_title": "طرق الدفع",
    "payment_message": "سيتم تنفيذ إدارة المدفوعات هنا",
    "current_balance": "الرصيد الحالي: {amount}",
    "location_message": "سيتم تنفيذ إعدادات الموقع هنا",
    "password_message": "سيتم تنفيذ وظيفة تغيير كلمة المرور هنا",
    "privacy_message": "سيتم عرض محتوى سياسة الخصوصية هنا",
    "contact_message": "سيتم عرض معلومات الاتصال وخيارات الدعم هنا",
    "faq_message": "سيتم عرض الأسئلة المتكررة هنا",
    "provider_mode": "وضع مقدم الخدمة",
    "user_mode": "وضع المستخدم",
    "receiving_service_requests": "أنت تستقبل طلبات الخدمة",
    "requesting_services": "أنت تطلب الخدمات"
  },
  "home": {
    "title": "الرئيسية",
    "your_location": "موقعك",
    "location_name": "اسم الموقع",
    "services": "الخدمات",
    "household_services": "الخدمات المنزلية",
    "professional_services": "الخدمات المهنية",
    "personal_services": "الخدمات الشخصية",
    "logistical_services": "الخدمات اللوجستية",
    "curated_stories": "القصص المختارة",
    "discover_horizons": "اكتشف آفاقاً جديدة",
    "join_provider": "انضم كمقدم خدمة",
    "join_as_service_provider": "انضم كمقدم خدمة",
    "top_providers": "أفضل مقدمي الخدمة",
    "service": "الخدمة"
  },
  "navigation": {
    "home": "الرئيسية",
    "orders": "الطلبات",
    "services": "الخدمات",
    "chat": "المحادثة",
    "profile": "الملف الشخصي",
    "curated_stories": "القصص المختارة"
  },
  "orders": {
    "my_orders": "طلباتي",
    "my_order": "طلبي",
    "search_placeholder": "سيارة، أثاث، تنظيف، ...",
    "pending": "في الانتظار",
    "underway": "قيد التنفيذ",
    "complete": "مكتمل",
    "cancelled": "ملغي",
    "orders_count": "طلبات",
    "no_orders_found": "لم يتم العثور على طلبات",
    "services_category": "فئة الخدمات",
    "services_subcategory": "فئة فرعية للخدمات",
    "order_details": "تفاصيل الطلب",
    "order_id": "رقم الطلب",
    "service": "الخدمة",
    "location": "الموقع",
    "status": "الحالة",
    "description": "الوصف",
    "view_details": "عرض التفاصيل",
    "edit_order": "تعديل الطلب",
    "cancel_order": "إلغاء الطلب",
    "select_services_type_to_complete_order": "اختر نوع الخدمات لإكمال الطلب",
    "add_order": "أضف طلبك",
    "choose_subcategory": "اختر الفئة الفرعية",
    "error_creating_order": "فشل في إنشاء الطلب",
    "order_created_successfully": "تم إنشاء الطلب بنجاح",
    "scheduled": "مجدول",
    "as_soon_as_possible": "في أسرع وقت ممكن",
    "Category": "الفئة",
    "Subcategory": "الفئة الفرعية",
    "view_my_order": "عرض طلبي",
    "services_type": "وقت الخدمة",
    "order_status": "حالة الطلب",
    "confirmed": "مؤكد",
    "in_progress": "قيد التنفيذ",
    "completed": "مكتمل",
    "order_date": "تاريخ الطلب",
    "service_provider": "مقدم الخدمة",
    "total_amount": "المبلغ الإجمالي",
    "payment_method": "طريقة الدفع",
    "order_items": "عناصر الطلب",
    "delivery_address": "عنوان التسليم",
    "special_instructions": "تعليمات خاصة",
    "track_order": "تتبع الطلب",
    "rate_order": "تقييم الطلب",
    "reorder": "إعادة الطلب",
    "order_history": "تاريخ الطلبات",
    "no_orders": "لم يتم العثور على طلبات",
    "no_orders_message": "لم تقم بتقديم أي طلبات بعد",
    "browse_services": "تصفح الخدمات",
    "loading_orders": "جاري تحميل الطلبات...",
    "error_loading_orders": "خطأ في تحميل الطلبات",
    "retry": "إعادة المحاولة",
    "available_offers": "العروض المتاحة",
    "loading_more_offers": "جاري تحميل المزيد من العروض...",
    "loading_offers": "جاري تحميل العروض...",
    "details": "التفاصيل",
    "accept": "قبول",
    "accept_offer": "قبول العرض",
    "accept_offer_confirmation": "هل أنت متأكد من أنك تريد قبول هذا العرض من {providerName}؟",
    "accepting_offer": "جاري قبول العرض...",
    "offer_accepted_successfully": "تم قبول العرض بنجاح!",
    "failed_to_accept_offer": "فشل في قبول العرض. يرجى المحاولة مرة أخرى.",
    "network_error": "خطأ في الشبكة. يرجى التحقق من الاتصال.",
    "offers": "العروض",
    "cancel_reason": "سبب الإلغاء",
    "close": "إغلاق",
    "reason_for_cancellation": "سبب الإلغاء",
    "specify_cancellation_reason": "يرجى تحديد سبب إلغاء الطلب",
    "loading_cancellation_reasons": "جاري تحميل أسباب الإلغاء...",
    "failed_to_load_cancel_reasons": "فشل في تحميل أسباب الإلغاء",
    "send": "إرسال",
    "select_cancellation_reason": "يرجى اختيار سبب الإلغاء",
    "cancelling_order": "جاري إلغاء الطلب...",
    "order_cancelled_successfully": "تم إلغاء الطلب بنجاح",
    "failed_to_cancel_order": "فشل في إلغاء الطلب. يرجى المحاولة مرة أخرى.",
    "edit_functionality_coming_soon": "سيتم إضافة وظيفة التعديل قريباً  ربما لاحقاً :D",
    "thank_you_feedback": "شكراً لك على ملاحظاتك!",
    "failed_to_submit_rating": "فشل في إرسال التقييم",
    "error_submitting_rating": "حدث خطأ أثناء إرسال تقييمك",
    "today_at": "اليوم في",
    "yesterday_at": "أمس في"
  },
  "messages": {
    "registration_successful": "تم التسجيل بنجاح",
    "login_successful": "تم تسجيل الدخول بنجاح",
    "verification_required": "التحقق مطلوب",
    "please_verify_phone": "يرجى التحقق من رقم هاتفك",
    "complete_profile": "إكمال الملف الشخصي",
    "please_complete_profile": "يرجى إكمال ملفك الشخصي",
    "otp_sent": "تم إرسال رمز التحقق بنجاح",
    "phone_verified": "تم التحقق من رقم الهاتف",
    "please_complete_profile_info": "يرجى إكمال معلومات ملفك الشخصي",
    "phone_number_already_registered": "رقم الهاتف مسجل بالفعل",
    "phone_already_in_use": "رقم الهاتف قيد الاستخدام بالفعل",
    "solutions": "الحلول:",
    "use_login_instead": "استخدم تسجيل الدخول بدلاً من ذلك",
    "try_different_number": "جرب رقماً مختلفاً",
    "contact_support": "اتصل بالدعم",
    "registration_successful_verify": "تم التسجيل بنجاح! يرجى التحقق من رقم هاتفك",
    "welcome": "أهلاً وسهلاً!",
    "phone_verified_complete": "تم التحقق من الهاتف! يرجى إكمال ملفك الشخصي",
    "network_error_check_connection": "خطأ في الشبكة. يرجى التحقق من الاتصال والمحاولة مرة أخرى.",
    "network_error_check_internet": "خطأ في الشبكة. تحقق من اتصالك بالإنترنت وحاول مرة أخرى",
    "please_wait": "يرجى الانتظار",
    "resend_code_in_seconds": "يمكنك إعادة إرسال الرمز خلال {seconds} ثانية",
    "code_resent": "تم إعادة إرسال الرمز",
    "new_verification_code_sent": "تم إرسال رمز تحقق جديد إلى هاتفك",
    "resend_failed": "فشل في إعادة الإرسال",
    "failed_resend_code": "فشل في إعادة إرسال الرمز. يرجى المحاولة مرة أخرى.",
    "failed_resend_check_connection": "فشل في إعادة إرسال الرمز. تحقق من الاتصال.",
    "feature_coming_soon": "الميزة قادمة قريباً",
    "forgot_password_feature": "ميزة نسيان كلمة المرور ستكون متاحة قريباً",
    "join_as_guest_clicked": "تم النقر على انضم كضيف",
    "welcome_back": "مرحباً بعودتك!",
    "unknown_error": "حدث خطأ غير معروف"
  },
  "language": {
    "english": "الإنجليزية",
    "arabic": "العربية",
    "language_changed": "تم تغيير اللغة",
    "language_changed_to": "تم تغيير اللغة إلى"
  },
  "provider": {
    "latest_orders": "أحدث الطلبات",
    "requests_sent_from_newest_to_oldest": "الطلبات المرسلة من الأحدث إلى الأقدم",
    "provider_name": "اسم مقدم الخدمة",
    "provider_category": "فئة مقدم الخدمة",
    "name_of_service_requester": "اسم طالب الخدمة",
    "no_orders_yet": "لا توجد طلبات بعد",
    "orders_will_appear_here": "ستظهر طلبات المستخدمين هنا عندما يطلبون خدماتك",
    "error_loading_orders": "خطأ في تحميل الطلبات"
  },
  "forms": {
    "required_field": "هذا الحقل مطلوب",
    "confirmation_invalid": "التأكيد غير متطابق",
    "invalid_format": "تنسيق غير صحيح",
    "min_length": "يجب أن يحتوي على {min} أحرف على الأقل",
    "max_length": "يجب أن يحتوي على أقل من {max} حرف",
    "passwords_not_match": "كلمات المرور غير متطابقة",
    "invalid_email": "عنوان بريد إلكتروني غير صحيح",
    "invalid_phone": "رقم هاتف غير صحيح",
    "phone_country_code": "يرجى تضمين رمز البلد",
    "password_weak": "كلمة المرور ضعيفة جداً",
    "name_required": "الاسم مطلوب",
    "name_min": "يجب أن يحتوي الاسم على {min} أحرف على الأقل",
    "name_max": "يجب أن يحتوي الاسم على أقل من {max} حرف",
    "name_invalid": "الاسم يحتوي على أحرف غير صحيحة",
    "email_required": "البريد الإلكتروني مطلوب",
    "email_invalid": "عنوان بريد إلكتروني غير صحيح",
    "url_required": "الرابط مطلوب",
    "url_invalid": "تنسيق الرابط غير صحيح",
    "first_name_required": "الاسم الأول مطلوب",
    "first_name_min": "يجب أن يحتوي الاسم الأول على {min} أحرف على الأقل",
    "first_name_max": "يجب أن يحتوي الاسم الأول على أقل من {max} حرف",
    "last_name_required": "الاسم الأخير مطلوب",
    "last_name_min": "يجب أن يحتوي الاسم الأخير على {min} أحرف على الأقل",
    "last_name_max": "يجب أن يحتوي الاسم الأخير على أقل من {max} حرف",
    "national_id_required": "رقم الهوية الوطنية مطلوب",
    "national_id_min": "يجب أن تحتوي الهوية الوطنية على {min} أحرف على الأقل",
    "gender_required": "الجنس مطلوب",
    "valid_gender": "يرجى اختيار جنس صحيح",
    "profile_photo_required": "صورة الملف الشخصي مطلوبة",
    "id_photo_required": "صورة الهوية مطلوبة",
    "enter_valid_email": "أدخل عنوان بريد إلكتروني صحيح",
    "max_photos": "الحد الأقصى 5 صور مسموح",
    "photo_added_successfully": "تم إضافة الصورة بنجاح",
    "error_adding_photo": "فشل في إضافة الصورة",
    "photo_removed": "تم إزالة الصورة",
    "phone_required": "الهاتف مطلوب",
    "phone_invalid": "رقم هاتف غير صحيح",
    "phone_min_length": "يجب أن يحتوي رقم الهاتف على 7 أرقام على الأقل",
    "phone_max_length": "يجب أن يحتوي رقم الهاتف على أقل من 15 رقم",
    "phone_invalid_format": "تنسيق رقم الهاتف غير صحيح",
    "password_min_length": "يجب أن تحتوي كلمة المرور على 6 أحرف على الأقل",
    "password_required": "كلمة المرور مطلوبة",
    "invalid_price_range": "نطاق السعر غير صحيح",
    "confirm_password_required": "يرجى تأكيد كلمة المرور الخاصة بك"
  },
  "dialogs": {
    "go_back_title": "الرجوع؟",
    "unsaved_changes": "لديك تغييرات غير محفوظة. هل أنت متأكد من أنك تريد الرجوع؟",
    "confirm_delete": "هل أنت متأكد من أنك تريد حذف هذا العنصر؟",
    "confirm_logout": "هل أنت متأكد من أنك تريد تسجيل الخروج؟",
    "select_image_source": "اختر مصدر الصورة",
    "camera": "الكاميرا",
    "gallery": "المعرض",
    "forgot_password_title": "نسيت كلمة المرور",
    "forgot_password_subtitle": "أدخل بريدك الإلكتروني لتلقي رابط إعادة التعيين",
    "discard_changes": "تجاهل التغييرات؟",
    "remove_profile_picture": "إزالة صورة الملف الشخصي",
    "remove_confirmation": "هل أنت متأكد من أنك تريد إزالة صورة ملفك الشخصي؟",
    "remove": "إزالة",
    "logout": "تسجيل الخروج",
    "delete_account": "حذف الحساب",
    "delete_account_warning": "هل أنت متأكد من أنك تريد حذف حسابك؟ هذا الإجراء لا يمكن التراجع عنه.",
    "final_confirmation": "التأكيد النهائي",
    "delete_account_final": "سيؤدي هذا إلى حذف حسابك وجميع البيانات نهائياً. هل أنت متأكد تماماً؟",
    "delete_forever": "حذف نهائي",
    "reset_password_confirm": "هل أنت متأكد من أنك تريد إعادة تعيين كلمة المرور؟ سيتم إرسال رمز التحقق إلى هاتفك.",
    "select_location": "اختر الموقع",
    "location_selection_coming_soon": "سيتم تنفيذ اختيار الموقع هنا",
    "about_renva": "حول رينفا",
    "about_renva_description": "رينفا هي منصتك الموثوقة للتواصل مع مقدمي الخدمات. ابحث عن محترفين مؤهلين لجميع احتياجاتك من الخدمات.",
    "select_gallery_photos": "اختر صور المعرض",
    "male": "ذكر",
    "female": "أنثى",
    "add_photo": "إضافة صورة",
    "delete_order_confirm": "هل أنت متأكد من أنك تريد حذف الطلب؟",
    "reason_for_delete": "سبب الحذف",
    "reason_for_delete_subtitle": "يرجى تحديد سبب حذف الطلب",
    "another_reason": "سبب آخر",
    "select_deletion_reason": "يرجى اختيار سبب الحذف",
    "provide_custom_deletion_reason": "يرجى تقديم سبب مخصص"
  },
  "errors": {
    "network_error": "خطأ في الاتصال بالشبكة",
    "server_error": "حدث خطأ في الخادم",
    "unknown_error": "حدث خطأ غير معروف",
    "login_failed": "فشل تسجيل الدخول. يرجى التحقق من بياناتك",
    "registration_failed": "فشل التسجيل. يرجى المحاولة مرة أخرى",
    "verification_failed": "فشل التحقق. يرجى المحاولة مرة أخرى",
    "profile_update_failed": "فشل في تحديث الملف الشخصي",
    "image_upload_failed": "فشل في رفع الصورة",
    "no_internet": "لا يوجد اتصال بالإنترنت",
    "timeout": "انتهت مهلة الطلب. يرجى المحاولة مرة أخرى",
    "unauthorized": "وصول غير مصرح به",
    "forbidden": "الوصول محظور",
    "not_found": "المورد غير موجود",
    "validation_error": "حدث خطأ في التحقق",
    "failed_to_select_image": "فشل في اختيار الصورة",
    "something_went_wrong": "حدث خطأ ما",
    "try_again": "يرجى المحاولة مرة أخرى",
    "failed_to_load_profile": "فشل في تحميل الملف الشخصي",
    "invalid_image_file": "ملف الصورة المحدد غير صحيح",
    "no_auth_token": "لم يتم العثور على رمز المصادقة. يرجى تسجيل الدخول مرة أخرى.",
    "failed_complete_profile": "فشل في إكمال الملف الشخصي. يرجى المحاولة مرة أخرى.",
    "api_call_failed": "فشل استدعاء واجهة برمجة التطبيقات",
    "processing_response_failed": "تم إكمال الملف الشخصي ولكن كانت هناك مشكلة في معالجة الاستجابة.",
    "user_data_not_found": "لم يتم العثور على بيانات المستخدم. يرجى تسجيل الدخول مرة أخرى.",
    "phone_not_found": "رقم الهاتف غير موجود في ملفك الشخصي.",
    "user_id_not_found": "لم يتم العثور على معرف المستخدم",
    "user_not_provider": "المستخدم ليس مزود خدمة",
    "mode_switch_failed": "فشل في تبديل الوضع. يرجى المحاولة مرة أخرى.",
    "loading_points": "خطأ في تحميل النقاط",
    "loading_balance": "خطأ في تحميل الرصيد",
    "delete_account_failed": "فشل في حذف الحساب",
    "failed_to_select_gallery_photo": "فشل في اختيار صورة المعرض",
    "failed_to_remove_image": "فشل في إزالة الصورة",
    "gallery_photo_required": "مطلوب صورة واحدة على الأقل من المعرض",
    "service_area_required": "يرجى اختيار منطقة الخدمة",
    "service_category_required": "يرجى اختيار فئة خدمة واحدة على الأقل",
    "deleting_order": "جاري حذف الطلب...",
    "network_error_check_connection": "خطأ في الشبكة. يرجى التحقق من الاتصال.",
    "all_profile_updates_failed": "فشلت جميع تحديثات الملف الشخصي. يرجى الاتصال بالدعم.",
    "verification_proceed_failed": "تم التحقق بنجاح ولكن فشل في المتابعة. يرجى المحاولة مرة أخرى.",
    "failed_to_load_stories": "فشل في تحميل القصص"
  },
  "success": {
    "login_successful": "تم تسجيل الدخول بنجاح",
    "registration_successful": "تم التسجيل بنجاح",
    "verification_successful": "تم التحقق بنجاح",
    "profile_updated": "تم تحديث الملف الشخصي بنجاح",
    "image_uploaded": "تم رفع الصورة بنجاح",
    "changes_saved": "تم حفظ التغييرات بنجاح",
    "account_created": "تم إنشاء الحساب بنجاح",
    "password_changed": "تم تغيير كلمة المرور بنجاح",
    "profile_photo_selected": "تم اختيار صورة الملف الشخصي بنجاح",
    "login_success": "تم تسجيل الدخول بنجاح",
    "registration_success": "تم التسجيل بنجاح",
    "verification_success": "تم التحقق من رقم الهاتف بنجاح",
    "password_reset_sent": "تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني",
    "image_selected": "تم اختيار الصورة",
    "profile_picture_updated": "تم تحديث صورة الملف الشخصي بنجاح",
    "notifications_enabled": "تم تفعيل الإشعارات",
    "notifications_disabled": "تم إلغاء تفعيل الإشعارات",
    "logged_out": "تم تسجيل خروجك بنجاح",
    "account_deleted": "تم حذف حسابك بنجاح",
    "profile_completed_welcome": "تم إكمال الملف الشخصي بنجاح! مرحباً بك في رينفا!",
    "id_photo_selected": "تم اختيار صورة الهوية بنجاح",
    "switched_to_provider_mode": "تم التبديل إلى وضع مزود الخدمة",
    "switched_to_user_mode": "تم التبديل إلى وضع المستخدم",
    "logout_offline": "تم تسجيل الخروج محلياً بسبب خطأ في الشبكة",
    "gallery_photo_added": "تم إضافة صورة المعرض",
    "order_deleted_successfully": "تم حذف الطلب بنجاح",
    "provider_profile_updated": "تم تحديث ملف مزود الخدمة بنجاح!",
    "profile_basic_updated": "ملف مزود الخدمة مقفل. جاري تحديث الملف الشخصي الأساسي فقط...",
    "profile_updated_categories_pending": "تم تحديث الملف الشخصي! (لم يتم حفظ الفئات - مزود الخدمة في انتظار الموافقة)",
    "phone_verified_set_password": "تم التحقق من الهاتف! الآن قم بتعيين كلمة المرور الجديدة.",
    "otp_sent_password_reset": "تم إرسال رمز التحقق لإعادة تعيين كلمة المرور"
  },
  "profile_menu": {
    "account": "الحساب",
    "loyalty_points": "نقاط الولاء",
    "payment": "الدفع",
    "my_location": "موقعي",
    "change_password": "تغيير كلمة المرور",
    "app_language": "لغة التطبيق",
    "app_notifications": "إشعارات التطبيق",
    "privacy_policy": "سياسة الخصوصية",
    "contact_us": "اتصل بنا",
    "faq": "الأسئلة الشائعة",
    "logout": "تسجيل الخروج",
    "delete_my_account": "حذف حسابي",
    "service_provider": "مقدم الخدمة",
    "provider": "مقدم الخدمة",
    "rating": "التقييم",
    "balance": "الرصيد",
    "current_balance": "الرصيد الحالي",
    "you_have_points": "لديك {points} نقطة ولاء",
    "earn_more_points": "احصل على المزيد من النقاط عن طريق إكمال الطلبات!",
    "payment_methods": "طرق الدفع",
    "payment_management": "سيتم تنفيذ إدارة المدفوعات هنا",
    "location_settings": "سيتم تنفيذ إعدادات الموقع هنا",
    "password_change": "سيتم تنفيذ وظيفة تغيير كلمة المرور هنا",
    "privacy_policy_content": "سيتم عرض محتوى سياسة الخصوصية هنا",
    "contact_info": "سيتم عرض معلومات الاتصال وخيارات الدعم هنا",
    "faq_content": "سيتم عرض الأسئلة المتكررة هنا",
    "provider_mode_label": "مزود الخدمة",
    "user_mode_label": "المستخدم",
    "deleting_account": "جاري الحذف...",
    "not_a_provider": "ليس مزود خدمة"
  },
  "stats": {
    "orders": "الطلبات",
    "points": "النقاط",
    "rating": "التقييم"
  },
  "buttons": {
    "join": "انضم",
    "saving": "جاري الحفظ...",
    "retry": "إعادة المحاولة"
  },
  "join_provider": {
    "select_services_type": "اختر نوع الخدمات",
    "welcome_message": "أهلاً وسهلاً بك في رينفا ... انضم إلينا كمقدم خدمة\nواحصل على جميع ميزات التطبيق",
    "loading_services": "جاري تحميل الخدمات...",
    "please_wait_loading": "يرجى الانتظار بينما نجلب الخدمات المتاحة",
    "failed_to_load_services": "فشل في تحميل الخدمات",
    "retry": "إعادة المحاولة",
    "next": "التالي",
    "loading": "جاري التحميل...",
    "next_with_count": "التالي ({count} محدد)",
    "services_available": "{count} خدمة متاحة",
    "no_services_available": "لا توجد خدمات متاحة",
    "no_services_selected": "لم يتم اختيار خدمات",
    "services_selected": "{count} خدمة محددة",
    "select_at_least_one": "يرجى اختيار خدمة واحدة على الأقل",
    "failed_to_load_retry": "فشل في تحميل الخدمات. يرجى المحاولة مرة أخرى.",
    "no_services_available_error": "لا توجد خدمات متاحة",
    "failed_to_select": "فشل في اختيار الخدمة",
    "failed_to_navigate": "فشل في الانتقال إلى النموذج",
    "unknown_service": "خدمة غير معروفة",
    "subcategories": "الفئات الفرعية",
    "providers": "مقدمو الخدمة",
    "up_to": "حتى",
    "error_prefix": "خطأ: "
  },
  "order_card": {
    "id_prefix": "رقم ",
    "view_offer": "عرض العرض",
    "view_details": "عرض التفاصيل",
    "cancel_service": "إلغاء الخدمة",
    "offers_received_single": "عرض مستلم",
    "offers_received_plural": "عروض مستلمة",
    "reason_of_cancellation": "سبب الإلغاء",
    "unknown_provider": "مقدم خدمة غير معروف",
    "service_provider_cancelled": "قام مقدم الخدمة بإلغاء الطلب",
    "service_provider": "مقدم الخدمة",
    "rating_and_review": "التقييم والمراجعة",
    "great_service": "خدمة رائعة!",
    "tap_to_rating": "اضغط للتقييم من فضلك"
  },
  "offer_details": {
    "view_offer": "مشاهدة العرض",
    "pictures": "الصور",
    "description": "الوصف",
    "default_description": "لوريم إيبسوم دولور سيت أميت، كونسيكتيتور أديبيسكينج إليت، سيد دو إيوسمود تيمبور إنكيديدنت أوت لابوري إت دولوري ماجنا أليكا. أوت إنيم أد مينيم فينيام، كويس نوسترود إكسيرسيتاشون",
    "price_range": "نطاق السعر",
    "date_and_time": "التاريخ والوقت",
    "delete": "حذف",
    "accept": "قبول",
    "accept_offer": "قبول العرض",
    "accept_offer_confirmation": "هل أنت متأكد من أنك تريد قبول هذا العرض من {providerName}؟",
    "cancel": "إلغاء",
    "delete_offer": "حذف العرض",
    "delete_offer_confirmation": "هل أنت متأكد من أنك تريد حذف هذا العرض؟",
    "accepting_offer": "جاري قبول العرض...",
    "offer_accepted_successfully": "تم قبول العرض بنجاح!",
    "failed_to_accept_offer": "فشل في قبول العرض. يرجى المحاولة مرة أخرى.",
    "network_error": "خطأ في الشبكة. يرجى التحقق من الاتصال.",
    "declining_offer": "جاري رفض العرض...",
    "offer_declined_successfully": "تم رفض العرض بنجاح!",
    "failed_to_decline_offer": "فشل في رفض العرض. يرجى المحاولة مرة أخرى.",
    "accept_success": "تم قبول العرض بنجاح!",
    "decline_success": "تم رفض العرض بنجاح!",
    "accept_failed": "فشل في قبول العرض. يرجى المحاولة مرة أخرى.",
    "decline_failed": "فشل في رفض العرض. يرجى المحاولة مرة أخرى.",
    "reviews": "مراجعات",
    "currency_sek": "كرونة سويدية",
    "created_at": "في",
    "close_image": "إغلاق الصورة"
  },
  "add_orders": {
    "add_order": "إضافة طلب",
    "select_services_type": "اختر نوع الخدمات لإكمال الطلب",
    "providers_available": "مقدم خدمة متاح",
    "provider_available_single": "مقدم خدمة متاح",
    "loading_subcategories": "الرجاء الانتظار ",
    "no_subcategories": "لا توجد فئات فرعية متاحة لـ {service}",
    "please_select_subcategory": "يرجى اختيار الخدمة",
    "service_description_1": "تلبية احتياجات تنظيف منزلك من الألف إلى الياء",
    "service_description_2": "الالتزام بالموعد النهائي المطلوب",
    "service_description_3": "ضمان السلامة الكاملة والسرية",
    "household_services": "الخدمات المنزلية",
    "professional_services": "الخدمات المهنية",
    "personal_services": "الخدمات الشخصية",
    "logistical_services": "الخدمات اللوجستية",
    "cleaning": "التنظيف",
    "washing": "الغسيل",
    "plant_care": "العناية بالنباتات",
    "pet_care": "رعاية الحيوانات الأليفة",
    "car_wash": "غسيل السيارات",
    "electrical_work": "الأعمال الكهربائية",
    "plumbing": "السباكة",
    "painting": "الطلاء",
    "personal_training": "التدريب الشخصي",
    "tutoring": "التدريس الخصوصي",
    "package_delivery": "توصيل الطرود",
    "moving": "النقل",
    "transportation": "المواصلات"
  },
  "add_order_details": {
    "select_service_type": "اختر نوع الخدمة",
    "service_type_subtitle": "اختر الوقت ونوع الخدمة التي تناسبك",
    "as_soon_as_possible": "في أسرع وقت ممكن",
    "specific_date": "تاريخ محدد",
    "invalid_category_selection": "اختيار فئة غير صحيح",
    "please_select_service_type": "يرجى اختيار نوع الخدمة",
    "continue": "المتابعة",
    "at_time": "في"
  },
  "complete_order": {
    "title": "أكمل طلبك",
    "price_range": "نطاق السعر",
    "description": "الوصف",
    "description_placeholder": "أضف وصف",
    "upload_photos": "رفع الصور",
    "upload_photo": "رفع صورة",
    "photos_count": "{count}/5 صور",
    "done": "تم",
    "syp_currency": "ل.س",
    "sek_currency": "كرونة"
  },
  "provider_home": {
    "welcome_future_provider": "مرحباً بمزود الخدمة المستقبلي!",
    "review_description": "نحن نراجع طلب تطبيق مزود الخدمة الخاص بك لضمان أفضل جودة خدمة لعملائنا.",
    "review_in_progress": "المراجعة قيد التقدم • من يوم إلى ثلاثة أيام",
    "what_awaits_you": "ما ينتظرك:",
    "receive_requests": "استقبال\nالطلبات",
    "earn_money": "كسب\nالمال",
    "build_reputation": "بناء\nالسمعة",
    "grow_business": "نمو\nالأعمال",
    "continue_as_customer": "المتابعة كعميل",
    "loading_more_orders": "تحميل المزيد من الطلبات...",
    "invalid_order_data": "بيانات طلب غير صحيحة",
    "provider_name_fallback": "اسم مزود الخدمة",
    "service_provider_fallback": "مزود خدمة",
    "unknown_customer": "عميل غير معروف",
    "customer_prefix": "العميل",
    "location_not_specified": "لم يتم تحديد الموقع",
    "service_request_fallback": "طلب خدمة",
    "name_of_services_requester": "اسم طالب الخدمة",
    "just_now": "الآن",
    "recently": "مؤخراً",
    "today": "اليوم",
    "day_ago": "يوم مضى",
    "days_ago": "أيام مضت",
    "hour_ago": "ساعة مضت",
    "hours_ago": "ساعات مضت",
    "min_ago": "دقيقة مضت",
    "mins_ago": "دقائق مضت",
    "monday": "الاثنين",
    "tuesday": "الثلاثاء",
    "wednesday": "الأربعاء",
    "thursday": "الخميس",
    "friday": "الجمعة",
    "saturday": "السبت",
    "sunday": "الأحد",
    "notifications_tapped": "تم النقر على الإشعارات",
    "filter_orders_tapped": "تم النقر على تصفية الطلبات",
    "close_button_tapped": "تم النقر على زر الإغلاق",
    "unable_to_view_order_details": "غير قادر على عرض تفاصيل الطلب"
  },
  "provider_orders": {
    "application_pending": "طلب مزود الخدمة قيد الانتظار...",
    "review_description": "طلب تطبيق مزود الخدمة الخاص بك قيد المراجعة حالياً من قبل فريقنا.",
    "approval_note": "ستتمكن من استقبال الطلبات بمجرد الموافقة عليك",
    "continue_as_customer": "المتابعة كعميل",
    "my_orders": "طلباتي",
    "search_orders": "البحث في الطلبات...",
    "loading_orders": "تحميل الطلبات...",
    "orders_count": "طلبات",
    "pending": "في الانتظار",
    "underway": "قيد التنفيذ",
    "complete": "مكتملة",
    "cancelled": "ملغية",
    "order_completed_success": "تم إكمال الطلب بنجاح!",
    "offer_cancelled_success": "تم إلغاء العرض بنجاح",
    "offer_deleted_success": "تم حذف العرض بنجاح!",
    "cancelling_offer": "جاري إلغاء العرض...",
    "complete_order_failed": "فشل في إكمال الطلب. يرجى المحاولة مرة أخرى.",
    "network_error": "خطأ في الشبكة. يرجى التحقق من اتصالك.",
    "cancel_reasons_failed": "فشل في تحميل أسباب الإلغاء",
    "loading_reasons_error": "خطأ في الشبكة أثناء تحميل الأسباب",
    "cancel_offer_failed": "فشل في إلغاء العرض. يرجى المحاولة مرة أخرى.",
    "delete_offer_failed": "فشل في إلغاء العرض.",
    "view_details_error": "خطأ في عرض تفاصيل الطلب"
  },
  "provider_order_card": {
    "id_prefix": "رقم التعريف ",
    "services_fallback": "الخدمات",
    "no_address": "لا يوجد عنوان",
    "view_details": "عرض التفاصيل",
    "delete_offer": "حذف العرض",
    "cancel_offer": "إلغاء العرض",
    "view_offers": "مشاهدة العرض",
    "your_offer": "عرضك:",
    "offer_accepted": "مقبول",
    "offer_pending": "قيد الانتظار",
    "offer_declined": "مرفوض",
    "order_cancelled": "تم إلغاء الطلب",
    "cancelled_by_customer": "تم إلغاء الطلب من قبل العميل",
    "order_completed": "تم إكمال الطلب",
    "completed_successfully": "تم إكمال الطلب بنجاح",
    "complete_order": "إكمال الطلب",
    "customer": "العميل",
    "success": "نجح",
    "delete_offer_title": "حذف العرض؟",
    "delete_offer_description": "سيؤدي هذا إلى إزالة عرضك نهائياً من هذا الطلب.",
    "delete_offer_cancel": "إلغاء",
    "delete_offer_confirm": "حذف",
    "cancel_offer_title": "إلغاء العرض؟",
    "cancel_offer_description": "ستحتاج إلى تقديم سبب لإلغاء هذا العرض.",
    "keep_offer": "الاحتفاظ بالعرض",
    "cancel_offer_confirm": "إلغاء العرض",
    "reason_for_cancellation": "سبب الإلغاء",
    "reason_description": "يرجى تحديد سبب إلغاء هذا العرض",
    "loading_reasons": "تحميل أسباب الإلغاء...",
    "no_reasons_available": "لا توجد أسباب إلغاء متاحة",
    "contact_support": "يرجى الاتصال بالدعم أو المحاولة مرة أخرى لاحقاً.",
    "retry": "إعادة المحاولة",
    "other_reason": "سبب آخر",
    "specify_reason": "يرجى تحديد سببك...",
    "cancel_offer_submit": "إلغاء العرض",
    "select_reason": "يرجى اختيار سبب الإلغاء",
    "provide_custom_reason": "يرجى تقديم سبب مخصص"
  },
  "hints": {
    "from": "من",
    "to": "إلى",
    "add_description": "إضافة وصف",
    "add_deletion_reason": "إضافة سبب آخر للحذف",
    "write_review_here": "اكتب مراجعتك هنا...",
    "time": "الوقت",
    "offer_details_description": "صف تفاصيل عرضك...",
    "enter_new_password": "أدخل كلمة المرور الجديدة",
    "confirm_new_password": "تأكيد كلمة المرور الجديدة"
  },
  "validation": {
    "confirm_password_required": "يرجى تأكيد كلمة المرور الخاصة بك",
    "passwords_do_not_match": "كلمات المرور غير متطابقة",
    "enter_valid_price": "يرجى إدخال سعر صحيح",
    "price_range_validation": "يجب أن يكون السعر بين {min} - {max} كرونة",
    "enter_valid_number": "يرجى إدخال رقم صحيح"
  },
  "deletion_reasons": {
    "change_mind": "غيرت رأيي",
    "no_longer_need": "لم أعد بحاجة إلى الخدمة",
    "provider_no_response": "لم يستجب مقدم الخدمة للرسائل",
    "high_prices": "أسعار مقدم الخدمة مرتفعة"
  },
  "provider_status": {
    "not_a_provider": "ليس مزود خدمة",
    "approved_provider": " مزود خدمة معتمد",
    "pending_approval": " في انتظار الموافقة",
    "application_rejected": " تم رفض الطلب",
    "provider_status_prefix": " حالة مزود الخدمة: "
  }
};
static const Map<String,dynamic> _en = {
  "common": {
    "welcome_to": "Welcome to",
    "back": "Back",
    "go_back": "Go Back",
    "cancel": "Cancel",
    "confirm": "Confirm",
    "save": "Save",
    "delete": "Delete",
    "edit": "Edit",
    "add": "Add",
    "remove": "Remove",
    "search": "Search",
    "filter": "Filter",
    "sort": "Sort",
    "loading": "Loading...",
    "error": "Error",
    "success": "Success",
    "warning": "Warning",
    "info": "Information",
    "yes": "Yes",
    "no": "No",
    "ok": "OK",
    "done": "Done",
    "next": "Next",
    "previous": "Previous",
    "skip": "Skip",
    "retry": "Retry",
    "refresh": "Refresh",
    "close": "Close",
    "open": "Open",
    "select": "Select",
    "upload": "Upload",
    "download": "Download",
    "send": "Send",
    "receive": "Receive",
    "view": "View",
    "hide": "Hide",
    "show": "Show",
    "user": "User",
    "no_phone": "No phone",
    "continue": "Continue",
    "submit": "Submit",
    "from": "From",
    "to": "To",
    "unknown_service": "Unknown Service",
    "unknown_subcategory": "Unknown Subcategory",
    "unknown_location": "Unknown Location",
    "unknown_user": "Unknown User",
    "no_description": "No description",
    "not_specified": "Not specified",
    "date_not_specified": "Date not specified",
    "time_not_specified": "Time not specified",
    "price_not_specified": "Price not specified",
    "no_description_available": "No description available",
    "service_request": "Service Request",
    "some_error": "Some error occurred"
  },
  "auth": {
    "login": "Login",
    "signup": "Sign Up",
    "logout": "Logout",
    "register": "Register",
    "login_title": "Login to your account.",
    "login_subtitle": "Enter the following info to reach your account",
    "signup_title": "Create New Account",
    "signup_subtitle": "Add your information to create new account",
    "phone_number": "Phone Number",
    "phone_placeholder": "Ex: +963 111 222 333",
    "password": "Password",
    "password_placeholder": "••• ••• •••",
    "confirm_password": "Confirm Password",
    "confirm_password_placeholder": "Confirm Password",
    "forgot_password": "Forget Password ?",
    "join_as_guest": "Join us a guest",
    "add_strong_password": "Add strong password",
    "create_account": "Create Account",
    "have_account": "Already have an account?",
    "no_account": "Don't have an account?",
    "sign_in_instead": "Sign in instead",
    "sign_up_instead": "Sign up instead",
    "forgot_password_title": "Forgot Password",
    "forgot_password_subtitle": "Enter your phone number to receive a verification code",
    "reset_password_title": "Reset Password",
    "reset_password_subtitle": "Enter your new password",
    "new_password": "New Password",
    "new_password_placeholder": "Enter new password",
    "password_changed": "Password changed successfully",
    "verification_code_sent": "Verification code sent successfully",
    "verification_code_resent": "Verification code resent"
  },
  "verification": {
    "title": "Verification",
    "subtitle": "Enter the 4-digit code sent to your phone",
    "code_label": "Verification Code",
    "code_placeholder": "Enter 4-digit code",
    "resend_code": "Resend Code",
    "resend_in": "Resend in {seconds}s",
    "seconds": "seconds",
    "verify": "Verify",
    "verification_sent": "Verification successful!",
    "verification_failed": "Verification failed",
    "invalid_code": "Invalid verification code",
    "code_expired": "Verification code has expired"
  },
  "profile": {
    "complete_profile": "Complete information's",
    "complete_subtitle": "add your information to create new account",
    "full_name": "Full Name",
    "full_name_placeholder": "USER NAME",
    "last_name": "Last Name",
    "last_name_placeholder": "LAST NAME",
    "email": "Email",
    "email_placeholder": "user.name@gmail.com",
    "national_number": "National number",
    "national_number_placeholder": "add national number",
    "gender": "Gender",
    "gender_placeholder": "Male",
    "male": "Male",
    "female": "Female",
    "profile_picture": "Profile Picture",
    "add_photo": "Add Photo",
    "add_profile_photo": "Add Profile Photo",
    "id_photo": "ID photo",
    "tap_to_add": "Tap to add",
    "profile_completed": "Profile completed successfully",
    "profile_not_saved": "Your profile information will not be saved. Do you want to go back?",
    "edit_profile": "Edit Profile",
    "name": "Name",
    "phone_number": "Phone number",
    "phone_placeholder": "+999 123 456 78",
    "select_profile_photo": "Select Profile Photo",
    "select_id_photo": "Select ID Photo",
    "take_new_photo": "Take a new photo",
    "choose_from_gallery": "Choose from gallery",
    "select_gender": "Select Gender",
    "failed_to_load": "Failed to Load Profile",
    "retry": "Retry",
    "account": "Account",
    "service_provider": "Service Provider",
    "provider_info": "Provider: {name}",
    "rating": "Rating: {rating}",
    "orders": "Orders",
    "points": "Points",
    "loyalty_points": "Loyalty Points",
    "payment": "Payment",
    "login_as_user": "Login as a user",
    "login_as_provider": "Login as a service provider",
    "select_image_source": "Select Image Source",
    "camera": "Camera",
    "gallery": "Gallery",
    "remove_picture": "Remove Picture",
    "remove_picture_confirm": "Are you sure you want to remove your picture?",
    "language_changed_to": "Language changed to {language}",
    "language_failed": "Failed to change language",
    "load_failed": "Failed to load profile data. Please try again.",
    "picture_updated": "Profile picture updated successfully",
    "picture_invalid": "Selected image file is invalid",
    "image_selection_failed": "Failed to select image",
    "notifications_enabled": "Notifications enabled",
    "notifications_disabled": "Notifications disabled",
    "logout_title": "Logout",
    "logout_confirm": "Are you sure you want to logout?",
    "logout_success": "Logged out successfully",
    "logout_offline": "Logged out locally due to network error",
    "logout_failed": "Failed to logout properly. Please try again.",
    "delete_account_title": "Delete Account",
    "delete_account_confirm": "Are you sure you want to delete your account? This action cannot be undone.",
    "delete_final_title": "Final Confirmation",
    "delete_final_confirm": "This will permanently delete your account and all data. Are you absolutely sure?",
    "deleting": "Deleting...",
    "delete_forever": "Delete Forever",
    "delete_success": "Account deleted successfully",
    "delete_failed": "Failed to delete account: {error}",
    "no_auth_token": "No authentication token found",
    "user_id_not_found": "User ID not found",
    "loyalty_points_title": "Loyalty Points",
    "loyalty_points_message": "You have {points} loyalty points",
    "loyalty_points_earn_more": "Earn more points by completing orders!",
    "payment_methods_title": "Payment Methods",
    "payment_message": "Payment management will be implemented here",
    "current_balance": "Current balance: {amount}",
    "location_message": "Location settings will be implemented here",
    "password_message": "Password change functionality will be implemented here",
    "privacy_message": "Privacy policy content will be shown here",
    "contact_message": "Contact information and support options will be shown here",
    "faq_message": "Frequently asked questions will be shown here",
    "provider_mode": "Provider Mode",
    "user_mode": "User Mode",
    "receiving_service_requests": "You're receiving service requests",
    "requesting_services": "You're requesting services"
  },
  "home": {
    "title": "Home",
    "your_location": "Your Location",
    "location_name": "Location Name",
    "services": "Services",
    "household_services": "Household Services",
    "professional_services": "Professional Services",
    "personal_services": "Personal Services",
    "logistical_services": "Logistical Services",
    "curated_stories": "Curated Stories",
    "discover_horizons": "Discover New Horizons",
    "join_provider": "Join Provider",
    "join_as_service_provider": "Join as Service Provider",
    "top_providers": "Top Providers",
    "service": "Service"
  },
  "navigation": {
    "home": "Home",
    "orders": "Orders",
    "services": "Services",
    "chat": "Chat",
    "profile": "Profile",
    "curated_stories": "Curated Stories"
  },
  "orders": {
    "my_orders": "My Orders",
    "my_order": "My Order",
    "search_placeholder": "Car, furniture, cleaning, ...",
    "pending": "Pending",
    "underway": "Underway",
    "complete": "Complete",
    "cancelled": "Cancelled",
    "orders_count": "Orders",
    "no_orders_found": "No orders found",
    "services_category": "Services Category",
    "services_subcategory": "Services Subcategory",
    "order_details": "Order Details",
    "order_id": "Order ID",
    "service": "Service",
    "location": "Location",
    "status": "Status",
    "description": "Description",
    "view_details": "View Details",
    "edit_order": "Edit Order",
    "cancel_order": "Cancel Order",
    "select_services_type_to_complete_order": "Select services type to complete order",
    "add_order": "Add your order",
    "choose_subcategory": "Choose Subcategory",
    "error_creating_order": "Failed to create order",
    "order_created_successfully": "Order created successfully",
    "scheduled": "Scheduled",
    "as_soon_as_possible": "As Soon As Possible",
    "Category": "Category",
    "Subcategory": "Subcategory",
    "view_my_order": "View My Order",
    "services_type": "Service Time",
    "order_status": "Order Status",
    "confirmed": "Confirmed",
    "in_progress": "In Progress",
    "completed": "Completed",
    "order_date": "Order Date",
    "service_provider": "Service Provider",
    "total_amount": "Total Amount",
    "payment_method": "Payment Method",
    "order_items": "Order Items",
    "delivery_address": "Delivery Address",
    "special_instructions": "Special Instructions",
    "track_order": "Track Order",
    "rate_order": "Rate Order",
    "reorder": "Reorder",
    "order_history": "Order History",
    "no_orders": "No Orders Found",
    "no_orders_message": "You haven't placed any orders yet",
    "browse_services": "Browse Services",
    "loading_orders": "Loading orders...",
    "error_loading_orders": "Error loading orders",
    "retry": "Retry",
    "available_offers": "Available Offers",
    "loading_more_offers": "Loading more offers...",
    "loading_offers": "Loading offers...",
    "details": "Details",
    "accept": "Accept",
    "accept_offer": "Accept Offer",
    "accept_offer_confirmation": "Are you sure you want to accept this offer from {providerName}?",
    "accepting_offer": "Accepting offer...",
    "offer_accepted_successfully": "Offer accepted successfully!",
    "failed_to_accept_offer": "Failed to accept offer. Please try again.",
    "network_error": "Network error. Please check your connection.",
    "offers": "Offers",
    "cancel_reason": "Cancel Reason",
    "close": "Close",
    "reason_for_cancellation": "Reason for Cancellation",
    "specify_cancellation_reason": "Please specify the reason for cancelling the order",
    "loading_cancellation_reasons": "Loading cancellation reasons...",
    "failed_to_load_cancel_reasons": "Failed to load cancellation reasons",
    "send": "Send",
    "select_cancellation_reason": "Please select a cancellation reason",
    "cancelling_order": "Cancelling order...",
    "order_cancelled_successfully": "Order cancelled successfully",
    "failed_to_cancel_order": "Failed to cancel order. Please try again.",
    "edit_functionality_coming_soon": "Edit functionality will be added here soon hehe maybe later :D",
    "thank_you_feedback": "Thank you for your feedback!",
    "failed_to_submit_rating": "Failed to submit rating",
    "error_submitting_rating": "An error occurred while submitting your rating",
    "today_at": "Today at",
    "yesterday_at": "Yesterday at"
  },
  "messages": {
    "registration_successful": "Registration successful",
    "login_successful": "Login successful",
    "verification_required": "Verification required",
    "please_verify_phone": "Please verify your phone number",
    "complete_profile": "Complete profile",
    "please_complete_profile": "Please complete your profile",
    "otp_sent": "OTP sent successfully",
    "phone_verified": "Phone number verified",
    "please_complete_profile_info": "Please complete your profile information",
    "phone_number_already_registered": "Phone number already registered",
    "phone_already_in_use": "Phone number is already in use",
    "solutions": "Solutions:",
    "use_login_instead": "Use login instead",
    "try_different_number": "Try a different number",
    "contact_support": "Contact support",
    "registration_successful_verify": "Registration successful! Please verify your phone number",
    "welcome": "Welcome!",
    "phone_verified_complete": "Phone verified! Please complete your profile",
    "network_error_check_connection": "Network error. Please check your connection and try again.",
    "network_error_check_internet": "Network error. Check your internet connection and try again",
    "please_wait": "Please Wait",
    "resend_code_in_seconds": "You can resend code in {seconds} seconds",
    "code_resent": "Code Resent",
    "new_verification_code_sent": "A new verification code has been sent to your phone",
    "resend_failed": "Resend Failed",
    "failed_resend_code": "Failed to resend code. Please try again.",
    "failed_resend_check_connection": "Failed to resend code. Check your connection.",
    "feature_coming_soon": "Feature Coming Soon",
    "forgot_password_feature": "Forgot password feature will be available soon",
    "join_as_guest_clicked": "Join as Guest clicked",
    "welcome_back": "Welcome Back!",
    "unknown_error": "Unknown error occurred"
  },
  "language": {
    "english": "English",
    "arabic": "العربية",
    "language_changed": "Language Changed",
    "language_changed_to": "Language changed to"
  },
  "provider": {
    "latest_orders": "Latest Order",
    "requests_sent_from_newest_to_oldest": "Requests sent from newest to oldest",
    "provider_name": "Provider Name",
    "provider_category": "provider category",
    "name_of_service_requester": "Name of the services requester",
    "no_orders_yet": "No orders yet",
    "orders_will_appear_here": "Orders from users will appear here when they request your services",
    "error_loading_orders": "Error loading orders"
  },
  "forms": {
    "required_field": "This field is required",
    "confirmation_invalid": "Confirmation does not match",
    "invalid_format": "Invalid format",
    "min_length": "Must be at least {min} characters",
    "max_length": "Must be less than {max} characters",
    "passwords_not_match": "Passwords do not match",
    "invalid_email": "Invalid email address",
    "invalid_phone": "Invalid phone number",
    "phone_country_code": "Please include country code",
    "password_weak": "Password is too weak",
    "name_required": "Name is required",
    "name_min": "Name must be at least {min} characters",
    "name_max": "Name must be less than {max} characters",
    "name_invalid": "Name contains invalid characters",
    "email_required": "Email is required",
    "email_invalid": "Invalid email address",
    "url_required": "URL is required",
    "url_invalid": "Invalid URL format",
    "first_name_required": "First name is required",
    "first_name_min": "First name must be at least {min} characters",
    "first_name_max": "First name must be less than {max} characters",
    "last_name_required": "Last name is required",
    "last_name_min": "Last name must be at least {min} characters",
    "last_name_max": "Last name must be less than {max} characters",
    "national_id_required": "National ID number is required",
    "national_id_min": "National ID must be at least {min} characters",
    "gender_required": "Gender is required",
    "valid_gender": "Please select a valid gender",
    "profile_photo_required": "Profile photo is required",
    "id_photo_required": "ID photo is required",
    "enter_valid_email": "Enter a valid email address",
    "max_photos": "Maximum 5 photos allowed",
    "photo_added_successfully": "Photo Added successfully",
    "error_adding_photo": "adding photo Failed",
    "photo_removed": "Photo removed",
    "phone_required": "Phone is required",
    "phone_invalid": "Invalid phone number",
    "phone_min_length": "Phone number must be at least 7 digits",
    "phone_max_length": "Phone number must be less than 15 digits",
    "phone_invalid_format": "Invalid phone number format",
    "password_required": "Password is required",
    "invalid_price_range": "Invalid price range",
    "password_min_length": "Password must be at least 6 characters",
    "confirm_password_required": "Please confirm your password"
  },
  "dialogs": {
    "go_back_title": "Go Back?",
    "unsaved_changes": "You have unsaved changes. Are you sure you want to go back?",
    "confirm_delete": "Are you sure you want to delete this item?",
    "confirm_logout": "Are you sure you want to logout?",
    "select_image_source": "Select Image Source",
    "camera": "Camera",
    "gallery": "Gallery",
    "forgot_password_title": "Forgot Password",
    "forgot_password_subtitle": "Enter your email to receive a reset link",
    "discard_changes": "Discard Changes?",
    "remove_profile_picture": "Remove Profile Picture",
    "remove_confirmation": "Are you sure you want to remove your profile picture?",
    "remove": "Remove",
    "logout": "Logout",
    "delete_account": "Delete Account",
    "delete_account_warning": "Are you sure you want to delete your account? This action cannot be undone.",
    "final_confirmation": "Final Confirmation",
    "delete_account_final": "This will permanently delete your account and all data. Are you absolutely sure?",
    "delete_forever": "Delete Forever",
    "reset_password_confirm": "Are you sure you want to reset your password? A verification code will be sent to your phone.",
    "select_location": "Select Location",
    "location_selection_coming_soon": "Location selection will be implemented here",
    "about_renva": "About Renva",
    "about_renva_description": "Renva is your trusted platform for connecting with service providers. Find qualified professionals for all your service needs.",
    "select_gallery_photos": "Select Gallery Photos",
    "male": "Male",
    "female": "Female",
    "add_photo": "Add Photo",
    "delete_order_confirm": "Are You Sure you want to delete the Request ?",
    "reason_for_delete": "Reason for Delete",
    "reason_for_delete_subtitle": "Please specify the reason for deleting the order",
    "another_reason": "Another reason",
    "select_deletion_reason": "Please select a deletion reason",
    "provide_custom_deletion_reason": "Please provide a custom reason"
  },
  "errors": {
    "network_error": "Network connection error",
    "server_error": "Server error occurred",
    "unknown_error": "An unknown error occurred",
    "login_failed": "Login failed. Please check your credentials",
    "registration_failed": "Registration failed. Please try again",
    "verification_failed": "Verification failed. Please try again",
    "profile_update_failed": "Failed to update profile",
    "image_upload_failed": "Failed to upload image",
    "no_internet": "No internet connection",
    "timeout": "Request timeout. Please try again",
    "unauthorized": "Unauthorized access",
    "forbidden": "Access forbidden",
    "not_found": "Resource not found",
    "validation_error": "Validation error occurred",
    "failed_to_select_image": "Failed to select image",
    "something_went_wrong": "Something went wrong",
    "try_again": "Please try again",
    "failed_to_load_profile": "Failed to Load Profile",
    "invalid_image_file": "Selected image file is invalid",
    "no_auth_token": "No authentication token found. Please login again.",
    "failed_complete_profile": "Failed to complete profile. Please try again.",
    "api_call_failed": "API call failed",
    "processing_response_failed": "Profile completed but there was an issue processing the response.",
    "user_data_not_found": "User data not found. Please login again.",
    "phone_not_found": "Phone number not found in your profile.",
    "user_id_not_found": "User ID not found",
    "user_not_provider": "User is not a provider",
    "mode_switch_failed": "Failed to switch mode. Please try again.",
    "loading_points": "Error loading points",
    "loading_balance": "Error loading balance",
    "delete_account_failed": "Failed to delete account",
    "failed_to_select_gallery_photo": "Failed to select gallery photo",
    "failed_to_remove_image": "Failed to remove image",
    "gallery_photo_required": "At least one gallery photo is required",
    "service_area_required": "Please select a service area",
    "service_category_required": "Please select at least one service category",
    "deleting_order": "Deleting order...",
    "network_error_check_connection": "Network error. Please check your connection.",
    "all_profile_updates_failed": "All profile updates failed. Please contact support.",
    "verification_proceed_failed": "Verification successful but failed to proceed. Please try again.",
    "failed_to_load_stories": "Failed to load stories"
  },
  "success": {
    "login_successful": "Login successful",
    "registration_successful": "Registration successful",
    "verification_successful": "Verification successful",
    "profile_updated": "Profile updated successfully",
    "image_uploaded": "Image uploaded successfully",
    "changes_saved": "Changes saved successfully",
    "account_created": "Account created successfully",
    "password_changed": "Password changed successfully",
    "profile_photo_selected": "Profile photo selected successfully",
    "login_success": "Login successful",
    "registration_success": "Registration successful",
    "verification_success": "Phone number verified successfully",
    "password_reset_sent": "Password reset link sent to your email",
    "image_selected": "Image Selected",
    "profile_picture_updated": "Profile picture updated successfully",
    "notifications_enabled": "Notifications enabled",
    "notifications_disabled": "Notifications disabled",
    "logged_out": "You have been successfully logged out",
    "account_deleted": "Your account has been successfully deleted",
    "profile_completed_welcome": "Profile completed successfully! Welcome to Renva!",
    "id_photo_selected": "ID photo selected successfully",
    "switched_to_provider_mode": "Switched to Provider mode",
    "switched_to_user_mode": "Switched to User mode",
    "logout_offline": "Logged out locally due to network error",
    "gallery_photo_added": "Gallery photo added",
    "order_deleted_successfully": "Order deleted successfully",
    "provider_profile_updated": "Provider profile updated successfully!",
    "profile_basic_updated": "Provider profile locked. Updating basic profile only...",
    "profile_updated_categories_pending": "Profile updated! (Categories not saved - provider pending approval)",
    "phone_verified_set_password": "Phone verified! Now set your new password.",
    "otp_sent_password_reset": "OTP Sent for Password Reset"
  },
  "profile_menu": {
    "account": "Account",
    "loyalty_points": "Loyalty Points",
    "payment": "Payment",
    "my_location": "My Location",
    "change_password": "Change Password",
    "app_language": "App Language",
    "app_notifications": "App Notifications",
    "privacy_policy": "Privacy Policy",
    "contact_us": "Contact Us",
    "faq": "FAQ",
    "logout": "Logout",
    "delete_my_account": "Delete my account",
    "service_provider": "Service Provider",
    "provider": "Provider",
    "rating": "Rating",
    "balance": "Balance",
    "current_balance": "Current balance",
    "you_have_points": "You have {points} loyalty points",
    "earn_more_points": "Earn more points by completing orders!",
    "payment_methods": "Payment Methods",
    "payment_management": "Payment management will be implemented here",
    "location_settings": "Location settings will be implemented here",
    "password_change": "Password change functionality will be implemented here",
    "privacy_policy_content": "Privacy policy content will be shown here",
    "contact_info": "Contact information and support options will be shown here",
    "faq_content": "Frequently asked questions will be shown here",
    "provider_mode_label": "Provider",
    "user_mode_label": "User",
    "deleting_account": "Deleting...",
    "not_a_provider": "Not a provider"
  },
  "stats": {
    "orders": "Orders",
    "points": "Points",
    "rating": "Rating"
  },
  "buttons": {
    "join": "Join",
    "saving": "Saving...",
    "retry": "Retry"
  },
  "join_provider": {
    "select_services_type": "Select Services Type",
    "welcome_message": "Welcome To Renva ... Join Us As A Service Provider\nAnd Get All The Features Of The App",
    "loading_services": "Loading services...",
    "please_wait_loading": "Please wait while we fetch available services",
    "failed_to_load_services": "Failed to load services",
    "retry": "Retry",
    "next": "Next",
    "loading": "Loading...",
    "next_with_count": "Next ({count} selected)",
    "services_available": "{count} services available",
    "no_services_available": "No services available",
    "no_services_selected": "No services selected",
    "services_selected": "{count} services selected",
    "select_at_least_one": "Please select at least one service",
    "failed_to_load_retry": "Failed to load services. Please try again.",
    "no_services_available_error": "No services available",
    "failed_to_select": "Failed to select service",
    "failed_to_navigate": "Failed to navigate to form",
    "unknown_service": "Unknown Service",
    "subcategories": "subcategories",
    "providers": "providers",
    "up_to": "Up to",
    "error_prefix": "Error: "
  },
  "order_card": {
    "id_prefix": "ID ",
    "view_offer": "View Offer",
    "view_details": "View Details",
    "cancel_service": "Cancel service",
    "offers_received_single": "offer received",
    "offers_received_plural": "offers received",
    "reason_of_cancellation": "Reason of cancellation",
    "unknown_provider": "Unknown Provider",
    "service_provider_cancelled": "The service provider cancelled the order",
    "service_provider": "Service Provider",
    "rating_and_review": "Rating & Review",
    "great_service": "Great service!",
    "tap_to_rating": "Tap to rate please"
  },
  "offer_details": {
    "view_offer": "View Offer",
    "pictures": "Pictures",
    "description": "Description",
    "default_description": "Lorem Ipsum Dolor Sit Amet, Consectetur Adipiscing Elit, Sed Do Eiusmod Tempor Incididunt Ut Labore Et Dolore Magna Aliqua. Ut Enim Ad Minim Veniam, Quis Nostrud Exercitation",
    "price_range": "Price Range",
    "date_and_time": "Date & Time",
    "delete": "Delete",
    "accept": "Accept",
    "accept_offer": "Accept Offer",
    "accept_offer_confirmation": "Are you sure you want to accept this offer from {providerName}?",
    "cancel": "Cancel",
    "delete_offer": "Delete Offer",
    "delete_offer_confirmation": "Are you sure you want to delete this offer?",
    "accepting_offer": "Accepting offer...",
    "offer_accepted_successfully": "Offer accepted successfully!",
    "failed_to_accept_offer": "Failed to accept offer. Please try again.",
    "network_error": "Network error. Please check your connection.",
    "declining_offer": "Declining offer...",
    "offer_declined_successfully": "Offer declined successfully!",
    "failed_to_decline_offer": "Failed to decline offer. Please try again.",
    "accept_success": "Offer accepted successfully!",
    "decline_success": "Offer declined successfully!",
    "accept_failed": "Failed to accept offer. Please try again.",
    "decline_failed": "Failed to decline offer. Please try again.",
    "reviews": "reviews",
    "currency_sek": "SEK",
    "created_at": "at",
    "close_image": "Close Image"
  },
  "add_orders": {
    "add_order": "Add Order",
    "select_services_type": "Select Services Type to complete order",
    "providers_available": "providers available",
    "provider_available_single": "provider available",
    "loading_subcategories": "Loading subcategories...",
    "no_subcategories": "No subcategories available for {service}",
    "please_select_subcategory": "Please select a subcategory",
    "service_description_1": "Meet your home cleaning needs from A to Z",
    "service_description_2": "Commitment to the required deadline",
    "service_description_3": "Ensuring complete safety and confidentiality",
    "household_services": "Household Services",
    "professional_services": "Professional Services",
    "personal_services": "Personal Services",
    "logistical_services": "Logistical Services",
    "cleaning": "Cleaning",
    "washing": "Washing",
    "plant_care": "Plant Care",
    "pet_care": "Pet Care",
    "car_wash": "Car Wash",
    "electrical_work": "Electrical Work",
    "plumbing": "Plumbing",
    "painting": "Painting",
    "personal_training": "Personal Training",
    "tutoring": "Tutoring",
    "package_delivery": "Package Delivery",
    "moving": "Moving",
    "transportation": "Transportation"
  },
  "add_order_details": {
    "select_service_type": "Select Service Type",
    "service_type_subtitle": "Choose the time and type of service that suits you",
    "as_soon_as_possible": "As Soon As Possible",
    "specific_date": "Specific Date",
    "invalid_category_selection": "Invalid category selection",
    "please_select_service_type": "Please select a service type",
    "continue": "Continue",
    "at_time": "at"
  },
  "complete_order": {
    "title": "Complete Your Order",
    "price_range": "Price Range",
    "description": "Description",
    "description_placeholder": "Add Description",
    "upload_photos": "Upload Photos",
    "upload_photo": "Upload Photo",
    "photos_count": "{count}/5 photos",
    "done": "Done",
    "syp_currency": "SYP",
    "sek_currency": "SEK"
  },
  "provider_home": {
    "welcome_future_provider": "Welcome Future Provider!",
    "review_description": "We're reviewing your provider application to ensure the best quality service for our customers.",
    "review_in_progress": "Review in progress • 1-3 days",
    "what_awaits_you": "What awaits you:",
    "receive_requests": "Receive\nRequests",
    "earn_money": "Earn\nMoney",
    "build_reputation": "Build\nReputation",
    "grow_business": "Grow\nBusiness",
    "continue_as_customer": "Continue as Customer",
    "loading_more_orders": "Loading more orders...",
    "invalid_order_data": "Invalid order data",
    "provider_name_fallback": "Provider Name",
    "service_provider_fallback": "Service Provider",
    "unknown_customer": "Unknown Customer",
    "customer_prefix": "Customer",
    "location_not_specified": "Location not specified",
    "service_request_fallback": "Service Request",
    "name_of_services_requester": "Name of the services requester",
    "just_now": "Just now",
    "recently": "Recently",
    "today": "Today",
    "day_ago": "day ago",
    "days_ago": "days ago",
    "hour_ago": "hour ago",
    "hours_ago": "hours ago",
    "min_ago": "min ago",
    "mins_ago": "mins ago",
    "monday": "Mon",
    "tuesday": "Tue",
    "wednesday": "Wed",
    "thursday": "Thu",
    "friday": "Fri",
    "saturday": "Sat",
    "sunday": "Sun",
    "notifications_tapped": "Notifications tapped",
    "filter_orders_tapped": "Filter orders tapped",
    "close_button_tapped": "Close button tapped",
    "unable_to_view_order_details": "Unable to view order details"
  },
  "provider_orders": {
    "application_pending": "Provider Application Pending...",
    "review_description": "Your provider application is currently under review by our team.",
    "approval_note": "You'll be able to receive orders once approved",
    "continue_as_customer": "Continue as Customer",
    "my_orders": "My Orders",
    "search_orders": "Search orders...",
    "loading_orders": "Loading orders...",
    "orders_count": "Orders",
    "pending": "Pending",
    "underway": "Underway",
    "complete": "Complete",
    "cancelled": "Cancelled",
    "order_completed_success": "Order completed successfully!",
    "offer_cancelled_success": "Offer cancelled successfully",
    "offer_deleted_success": "Offer deleted successfully!",
    "cancelling_offer": "Cancelling offer...",
    "complete_order_failed": "Failed to complete order. Please try again.",
    "network_error": "Network error. Please check your connection.",
    "cancel_reasons_failed": "Failed to load cancel reasons",
    "loading_reasons_error": "Network error while loading reasons",
    "cancel_offer_failed": "Failed to cancel offer. Please try again.",
    "delete_offer_failed": "Failed to cancel offer.",
    "view_details_error": "Error viewing order details"
  },
  "provider_order_card": {
    "id_prefix": "ID ",
    "services_fallback": "Services",
    "no_address": "No address",
    "view_details": "View details",
    "delete_offer": "Delete offer",
    "cancel_offer": "Cancel offer",
    "view_offers": "View Offers",
    "your_offer": "Your offer:",
    "offer_accepted": "Accepted",
    "offer_pending": "Pending",
    "offer_declined": "Declined",
    "order_cancelled": "Order cancelled",
    "cancelled_by_customer": "Order was cancelled by customer",
    "order_completed": "Order Completed",
    "completed_successfully": "Order completed successfully",
    "complete_order": "Complete Order",
    "customer": "Customer",
    "success": "Success",
    "delete_offer_title": "Delete Offer?",
    "delete_offer_description": "This will permanently remove your offer from this order.",
    "delete_offer_cancel": "Cancel",
    "delete_offer_confirm": "Delete",
    "cancel_offer_title": "Cancel Offer?",
    "cancel_offer_description": "You will need to provide a reason for cancelling this offer.",
    "keep_offer": "Keep Offer",
    "cancel_offer_confirm": "Cancel Offer",
    "reason_for_cancellation": "Reason for Cancellation",
    "reason_description": "Please specify the reason for cancelling this offer",
    "loading_reasons": "Loading cancel reasons...",
    "no_reasons_available": "No cancel reasons available",
    "contact_support": "Please contact support or try again later.",
    "retry": "Retry",
    "other_reason": "Other reason",
    "specify_reason": "Please specify your reason...",
    "cancel_offer_submit": "Cancel Offer",
    "select_reason": "Please select a cancellation reason",
    "provide_custom_reason": "Please provide a custom reason"
  },
  "hints": {
    "from": "From",
    "to": "To",
    "add_description": "Add Description",
    "add_deletion_reason": "Add Another Reason For Deletion",
    "write_review_here": "Write your review here...",
    "time": "Time",
    "offer_details_description": "Describe your offer details...",
    "enter_new_password": "Enter new password",
    "confirm_new_password": "Confirm new password"
  },
  "validation": {
    "confirm_password_required": "Please confirm your password",
    "passwords_do_not_match": "Passwords do not match",
    "enter_valid_price": "Please enter a valid price",
    "price_range_validation": "Price must be between {min} - {max} SEK",
    "enter_valid_number": "Please enter a valid number"
  },
  "deletion_reasons": {
    "change_mind": "Change my mind",
    "no_longer_need": "I no longer need the service",
    "provider_no_response": "The service provider did not respond to messages",
    "high_prices": "Service provider prices are high"
  },
  "provider_status": {
    "not_a_provider": "Not a provider",
    "approved_provider": " Approved Provider",
    "pending_approval": " Pending Approval",
    "application_rejected": " Application Rejected",
    "provider_status_prefix": " Provider Status: "
  }
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": _ar, "en": _en};
}
